# Generated by Django 5.2 on 2025-04-17 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField()),
                ('services', models.CharField(max_length=300)),
                ('about', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('portfolio_1', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('portfolio_2', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('portfolio_3', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('portfolio_4', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('portfolio_5', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
