# Generated by Django 5.2 on 2025-04-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_banned_professionalprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
